apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.name }}-building-apps-svc"
  labels:
    app: kudeskills
spec:
  selector:
    app: kudeskills
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

